@startuml
start

:получить список активных треков;

:загрузка конфигурации;

if (доступен источник?) then (да)

:получить метрики по треку;

:пересчитать агрегаты;

:записать метрики;

else (нет)

:записать ошибку;

endif 

:статус jobrun;

stop
@enduml
